workflow_inputs:
  seed:
    type: integer
    required: true

tasks:
  create_data:
    script: >
      python create_data.py
      --seed ${{ workflow_inputs.seed }}
      --output-dir ${{ outputs.directory }}
    container_image: "ghcr.io/flyteorg/flytekit:py3.11-1.13.6b2"
    resources:
      mem: 1Gi
      cpu: "1"

  compute_statistics:
    needs: [create_data]
    script: >
      python compute_statistics.py
      --input-dir ${{ create_data.directory }}
      --output-dir ${{ outputs.directory }}
    container_image: "ghcr.io/flyteorg/flytekit:py3.11-1.13.6b2"
    resources:
      mem: 1Gi
      cpu: "1"
